// Backend responses for the commands views call on mount (tests only; mirrors the Rust DTOs).
export const responses: Record<string, unknown> = {
  agent_logs: [],
  list_messages: [],
  list_events: [],
  memory_files: [],
  git_overview: null,
  load_workspace: null,
  save_workspace: null,
  recent_projects: [],
  list_agent_providers: [
    { id: "claude-code", name: "Claude Code", description: "CLI", available: true, installed: true, detail: "Claude Code 2.0" },
    { id: "codex", name: "Codex", description: "CLI", available: false, installed: true, detail: "Codex CLI detected · adapter not available yet" },
  ],
  detect_claude: { installed: true, path: null, version: "2.0.0", loggedIn: true, authMethod: null, subscription: null, error: null },
  app_info: { version: "0.1.0", dataDir: "C:/data", logDir: "C:/logs" },
  permission_rules: [],
  agent_sessions: [],
  claude_environment: {
    cli: { installed: true, path: "C:/bin/claude.exe", version: "2.1.0", loggedIn: true, authMethod: "oauth", subscription: "max", error: null },
    capturedAt: "2026-01-01T00:00:00Z",
    models: [{ value: "default", displayName: "Default", description: "Recommended" }, { value: "opus", displayName: "Opus", description: "Most capable", supportsEffort: true, supportedEffortLevels: ["low", "high"], supportsFastMode: true }],
    commands: [{ name: "review", description: "Review a PR", argumentHint: "<pr>" }],
    agents: [],
    account: { email: "dev@example.com" },
    permissionMode: "default",
    outputStyle: "default",
    outputStyles: [],
    fastMode: { state: "off", disabledReason: null },
    mcpServers: [{ name: "fs", status: "connected", config: { type: "stdio" }, scope: "project" }],
    context: { totalTokens: 20000, maxTokens: 200000, percentage: 10, categories: [{ name: "System prompt", tokens: 3000, kind: "system" }] },
    usage: { session: { total_cost_usd: 0 }, rate_limits: { five_hour: { utilization: 12, resets_at: "2026-01-01T05:00:00Z" } } },
    settings: { effective: { model: "opus" } },
    plugins: [],
    unavailable: [],
  },
  claude_command_tree: {
    path: [],
    aliases: [],
    usage: "claude [options]",
    signature: "",
    description: "Claude Code",
    arguments: [],
    options: [{ flags: "--model <model>", long: "--model", short: null, value: "<model>", description: "Model", choices: [], default: null, category: "" }],
    subcommands: [{ path: ["mcp", "list"], aliases: [], usage: "", signature: "", description: "List servers", arguments: [], options: [], subcommands: [], category: "mcp" }],
    category: "",
  },
  list_skills: [],
  list_decisions: [],
  pty_list: [],
  app_settings: { claudePath: null },
  system_report: { os: "Windows", osVersion: "11", arch: "x86_64", cpu: "CPU", cpuCores: 8, memoryTotalBytes: 16e9, memoryUsedBytes: 8e9, gpus: [], disks: [] },
  project_insights: { languages: [{ language: "Rust", files: 10 }], frameworks: [], dependencies: {}, filesScanned: 10 },
  project_environment: { project: [], tools: [{ key: "git", label: "Git", detected: true, detail: "git 2.45" }], projectTypes: [] },
  github_status: { cliInstalled: true, authenticated: false, account: null, repo: null, detail: null },
  master_status: {
    active: false,
    domains: [{ key: "github", label: "GitHub", enabled: true, available: false, level: 0, detail: "gh not signed in" }],
    centralPermissions: { fs_read: "allow", fs_write: "ask", fs_execute: "ask", network: "ask", git_read: "allow", git_write: "ask", github_read: "ask", github_write: "deny", github_admin: "deny", ssh_read: "deny", ssh_execute: "deny", mcp: "ask" },
  },
  list_commands: [],
  project_backups: [],
};
