// NEXUS addition: pure helpers of the NEXUS HQ overlay (signs, click areas,
// connections). The rooms themselves (floors, walls, furniture) are real map
// tiles generated by data/nexusHq.ts.
import { doorOf, type HqRoom } from '../../data/nexusHq';

const T = 32;

export type Rect = { x: number; y: number; w: number; h: number };

/** The room in world px. */
export function roomBounds(r: Pick<HqRoom, 'x' | 'y' | 'w' | 'h'>): Rect {
  return { x: r.x * T, y: r.y * T, w: r.w * T, h: r.h * T };
}

/** Sign text: the room's name (already in the AI World language) and its real agent count. */
export function signText(r: Pick<HqRoom, 'name'>, count: number): string {
  const name = r.name.trim() || '?';
  return count > 0 ? `${name} · ${count}` : name;
}

/** Center of the sign, on the room's top wall (world px). */
export function signAnchor(r: Pick<HqRoom, 'x' | 'y' | 'w'>): { x: number; y: number } {
  return { x: (r.x + r.w / 2) * T, y: r.y * T + T / 2 };
}

/** The door tile's center (world px). */
export function doorCenter(r: HqRoom): { x: number; y: number } {
  const d = doorOf(r);
  return { x: d.x * T + T / 2, y: d.y * T + T / 2 };
}

/** Lines between the doors of connected rooms (archived or unknown rooms skipped). */
export function connectionLines(
  rooms: HqRoom[],
  connections: { from: string; to: string }[],
): { from: string; to: string; a: { x: number; y: number }; b: { x: number; y: number } }[] {
  const byId = new Map(rooms.map((r) => [r.id, r]));
  const out = [];
  for (const c of connections) {
    const a = byId.get(c.from);
    const b = byId.get(c.to);
    if (!a || !b || a === b) continue;
    out.push({ from: c.from, to: c.to, a: doorCenter(a), b: doorCenter(b) });
  }
  return out;
}

/** Created less than `ms` ago (Safe Mode leaves the newest additions out). */
export function isRecent(r: Pick<HqRoom, 'createdAt'>, now: number, ms = 15 * 60_000): boolean {
  if (!r.createdAt) return false;
  const t = Date.parse(r.createdAt);
  return Number.isFinite(t) && now - t < ms && now >= t;
}

/** Room under a world-px point (click on a room's floor). */
export function roomAt(rooms: HqRoom[], x: number, y: number): HqRoom | undefined {
  return rooms.find((r) => x >= r.x * T && x < (r.x + r.w) * T && y >= r.y * T && y < (r.y + r.h) * T);
}
