//! Characters: from NEXUS agents, custom definitions or generated by Claude.

use std::path::{Path, PathBuf};

use serde::{Deserialize, Serialize};
use serde_json::Value;

use pcc_ai::provider::{ChatMessage, ChatRequest};
use pcc_ai::router::{self, Journal, Route, RouteDecision, RouteRequest, TaskKind};
use pcc_core::{AiEngineSettings, Error, Result};

use crate::model::{Character, ConversationLine, Relationship};

/// What is needed from a NEXUS agent to make a character.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
#[serde(rename_all = "camelCase", default)]
pub struct AgentSeed {
    pub id: String,
    pub name: String,
    pub role: String,
    pub is_central: bool,
    pub model: Option<String>,
    pub power: Option<String>,
    pub skills_enabled: bool,
    pub connections: Vec<String>,
    pub recent_tasks: Vec<String>,
}

fn slug(s: &str) -> String {
    pcc_core::ids::slugify(s)
}

/// One character per agent, linked to it; workers report to Central.
pub fn from_agents(agents: &[AgentSeed]) -> Vec<Character> {
    let central = agents.iter().find(|a| a.is_central).map(|a| a.name.clone());
    agents
        .iter()
        .enumerate()
        .map(|(i, a)| {
            let mut relationships = Vec::new();
            if a.is_central {
                for w in agents.iter().filter(|w| !w.is_central) {
                    relationships.push(Relationship { with: w.name.clone(), kind: "coordinates".into() });
                }
            } else if let Some(c) = &central {
                relationships.push(Relationship { with: c.clone(), kind: "reports to".into() });
            }
            let mut goals = vec![if a.is_central {
                "Keep the team on track and deliver missions".to_string()
            } else {
                format!("Deliver work as {}", a.role)
            }];
            goals.extend(a.recent_tasks.iter().take(3).cloned());
            Character {
                id: slug(&a.name),
                name: a.name.clone(),
                nexus_agent: Some(a.id.clone()),
                personality: if a.is_central {
                    "the calm orchestrator of the team".into()
                } else {
                    format!("a focused specialist: {}", a.role)
                },
                goals,
                skills: if a.skills_enabled { vec!["Claude Code skills".into()] } else { vec![] },
                tools: vec!["Claude Code".into()],
                mcp: a.connections.clone(),
                model: a.model.clone(),
                autonomy: a.power.clone().unwrap_or_else(|| "custom".into()),
                relationships,
                sprite: format!("f{}", i % 8 + 1),
                x: 38.0,
                y: 19.0,
                ..Default::default()
            }
        })
        .collect()
}

/// Runs a one-shot Claude Code prompt without tools and returns its text.
fn ask_claude(claude: &Path, model: &str, prompt: &str, budget_usd: f64) -> Result<String> {
    let dir = std::env::temp_dir();
    let out = pcc_claude::process::std_command(claude)
        .args([
            "-p",
            "--output-format",
            "json",
            "--model",
            model,
            "--tools",
            "",
            "--strict-mcp-config",
            "--disable-slash-commands",
            "--no-session-persistence",
            "--max-budget-usd",
            &format!("{budget_usd:.2}"),
            prompt,
        ])
        .current_dir(dir)
        .output()
        .map_err(|e| Error::Process(format!("cannot run Claude Code: {e}")))?;
    let v: Value = serde_json::from_slice(&out.stdout).map_err(|_| {
        Error::Process(format!("unexpected Claude Code output: {}", String::from_utf8_lossy(&out.stderr).trim()))
    })?;
    if v.get("is_error").and_then(Value::as_bool).unwrap_or(false) {
        return Err(Error::Process(v.get("result").and_then(Value::as_str).unwrap_or("Claude Code error").into()));
    }
    Ok(v.get("result").and_then(Value::as_str).unwrap_or("").to_string())
}

/// The model that writes world text: Claude through a one-shot Claude Code
/// call, or the local runtime, as decided by the ModelRouter.
#[derive(Debug, Clone)]
pub enum WorldLlm {
    Claude { claude: PathBuf, model: String },
    Local { ai: AiEngineSettings, model: String },
}

impl WorldLlm {
    pub fn label(&self) -> String {
        match self {
            WorldLlm::Claude { model, .. } => format!("Claude ({model})"),
            WorldLlm::Local { ai, model } => format!("{} ({model})", pcc_ai::runtime_name(&ai.local.runtime)),
        }
    }

    fn ask(&self, prompt: &str, budget_usd: f64) -> Result<String> {
        match self {
            WorldLlm::Claude { claude, model } => ask_claude(claude, model, prompt, budget_usd),
            WorldLlm::Local { ai, model } => {
                let req = ChatRequest {
                    model: model.clone(),
                    messages: vec![ChatMessage::user(prompt)],
                    temperature: Some(0.8),
                    max_tokens: Some(700),
                    // qwen3 & co: answer directly, the JSON is what matters.
                    think: pcc_ai::catalog::find(model).filter(|m| m.thinking).map(|_| false),
                    ..Default::default()
                };
                let text = pcc_ai::provider_for(ai).chat(&req)?.content;
                // Reasoning models may still print their thoughts first.
                Ok(match text.rfind("</think>") {
                    Some(i) => text[i + "</think>".len()..].to_string(),
                    None => text,
                })
            }
        }
    }
}

/// Chooses the engine for world text with the ModelRouter and journals the
/// decision. Blocking: checks the local runtime when the mode may use it.
pub fn world_llm(
    ai: &AiEngineSettings,
    task: TaskKind,
    claude_model: &str,
    journal: Option<&Journal>,
) -> Result<(WorldLlm, RouteDecision)> {
    let cap = if ai.mode == pcc_core::AiMode::Claude { router::LocalCapacity::default() } else { pcc_ai::capacity(ai) };
    let req = RouteRequest { task, ..Default::default() };
    let mut decision = router::route(ai.mode, &req, &cap);
    if decision.provider == Route::Unavailable && ai.fallback == pcc_core::FallbackPolicy::SwitchToClaude {
        decision = RouteDecision {
            provider: Route::Claude,
            model: None,
            reason: format!("fallback to Claude: {}", decision.reason),
            rule: "fallback-switch-to-claude".into(),
        };
    }
    if let Some(j) = journal {
        j.record("ai-world", ai.mode, &req, &decision);
    }
    let llm = match decision.provider {
        Route::Local => WorldLlm::Local { ai: ai.clone(), model: decision.model.clone().unwrap_or_default() },
        Route::Claude => {
            let claude =
                pcc_claude::find_claude().ok_or_else(|| Error::Process("Claude Code was not detected".into()))?;
            WorldLlm::Claude { claude, model: claude_model.to_string() }
        }
        Route::Unavailable => return Err(Error::invalid(format!("Local AI unavailable: {}", decision.reason))),
    };
    Ok((llm, decision))
}

/// Extracts the first JSON array from a model answer (tolerates code fences).
pub fn json_array(text: &str) -> Result<Vec<Value>> {
    let start = text.find('[').ok_or_else(|| Error::invalid("no JSON array in the answer"))?;
    let end = text.rfind(']').ok_or_else(|| Error::invalid("no JSON array in the answer"))?;
    serde_json::from_str(&text[start..=end]).map_err(|e| Error::invalid(format!("invalid JSON from the model: {e}")))
}

/// Asks the world model for `count` characters fitting the description. Blocking; may cost tokens.
pub fn generate(llm: &WorldLlm, description: &str, count: usize) -> Result<Vec<Character>> {
    let prompt = format!(
        "Create {count} distinct characters for a small simulated world described as: {description}\n\
         Answer ONLY with a JSON array of objects with keys: name (string), personality (one sentence), \
         goals (array of 1-3 short strings), skills (array of strings)."
    );
    let raw = llm.ask(&prompt, 0.25)?;
    let items = json_array(&raw)?;
    Ok(items
        .into_iter()
        .take(count)
        .enumerate()
        .filter_map(|(i, v)| {
            let name = v.get("name")?.as_str()?.to_string();
            let list = |k: &str| {
                v.get(k)
                    .and_then(Value::as_array)
                    .map(|a| a.iter().filter_map(|x| x.as_str().map(str::to_string)).collect())
                    .unwrap_or_default()
            };
            Some(Character {
                id: slug(&name),
                personality: v.get("personality").and_then(Value::as_str).unwrap_or("").to_string(),
                goals: list("goals"),
                skills: list("skills"),
                sprite: format!("f{}", i % 8 + 1),
                autonomy: "normal".into(),
                x: 10.0,
                y: 16.0,
                name,
                ..Default::default()
            })
        })
        .collect())
}

/// Generates a short simulated conversation between two characters. Blocking; may cost tokens.
pub fn converse(
    llm: &WorldLlm,
    world: &str,
    a: &Character,
    b: &Character,
    room: &str,
) -> Result<Vec<ConversationLine>> {
    let prompt = format!(
        "Simulated world: {world}. In the {room}, {} ({}; goals: {}) meets {} ({}; goals: {}).\n\
         Write their short conversation: 4 to 6 lines. Answer ONLY with a JSON array of {{\"speaker\": name, \"text\": line}}.",
        a.name, a.personality, a.goals.join("; "), b.name, b.personality, b.goals.join("; ")
    );
    let raw = llm.ask(&prompt, 0.10)?;
    Ok(json_array(&raw)?
        .into_iter()
        .filter_map(|v| {
            Some(ConversationLine {
                speaker: v.get("speaker")?.as_str()?.to_string(),
                text: v.get("text")?.as_str()?.to_string(),
                ts: pcc_core::now(),
            })
        })
        .collect())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn agents_become_linked_characters() {
        let seeds = vec![
            AgentSeed {
                id: "central".into(),
                name: "Central".into(),
                role: "Orchestrator".into(),
                is_central: true,
                ..Default::default()
            },
            AgentSeed {
                id: "roblox".into(),
                name: "Roblox Agent".into(),
                role: "Roblox systems".into(),
                skills_enabled: true,
                connections: vec!["roblox-studio".into()],
                recent_tasks: vec!["Implement drone formation".into()],
                ..Default::default()
            },
        ];
        let c = from_agents(&seeds);
        assert_eq!(c[0].nexus_agent.as_deref(), Some("central"));
        assert_eq!(c[0].relationships[0].with, "Roblox Agent");
        assert_eq!(c[1].relationships[0].kind, "reports to");
        assert_eq!(c[1].mcp, vec!["roblox-studio"]);
        assert!(c[1].goals.contains(&"Implement drone formation".to_string()));
        assert_ne!(c[0].sprite, c[1].sprite);
    }

    #[test]
    fn world_text_follows_the_router() {
        let dir = tempfile::tempdir().unwrap();
        let j = Journal::new(dir.path().join("routing.jsonl"));
        let mut ai = AiEngineSettings { mode: pcc_core::AiMode::Local, ..Default::default() };
        ai.local.base_url = "http://127.0.0.1:9".into();
        ai.local.model = Some("qwen3:8b".into());
        let err = world_llm(&ai, TaskKind::NpcDialogue, "haiku", Some(&j)).unwrap_err();
        assert!(err.to_string().contains("Local AI unavailable"));
        assert_eq!(j.recent(5)[0].decision.provider, Route::Unavailable);
    }

    /// Needs the local Ollama with llama3: a world line written by the local model, journaled.
    #[test]
    #[ignore]
    fn live_world_text_on_local_llama3() {
        let dir = tempfile::tempdir().unwrap();
        let j = Journal::new(dir.path().join("routing.jsonl"));
        let mut ai = AiEngineSettings { mode: pcc_core::AiMode::Hybrid, ..Default::default() };
        ai.local.model = Some("llama3".into());
        let (llm, d) = world_llm(&ai, TaskKind::NpcDialogue, "haiku", Some(&j)).unwrap();
        assert_eq!(d.provider, Route::Local, "{d:?}");
        let text = llm.ask("Answer ONLY with a JSON array of one string: a greeting.", 0.0).unwrap();
        assert!(json_array(&text).is_ok(), "{text}");
        assert_eq!(j.recent(1)[0].decision.rule, "hybrid-light-local");
    }

    #[test]
    fn extracts_json_arrays_from_answers() {
        assert_eq!(json_array("Here:\n```json\n[{\"a\":1}]\n```").unwrap().len(), 1);
        assert!(json_array("no json").is_err());
    }
}
