//! Characters: from NEXUS agents, custom definitions or generated by Claude.

use std::path::Path;

use serde::{Deserialize, Serialize};
use serde_json::Value;

use pcc_core::{Error, Result};

use crate::model::{Character, ConversationLine, Relationship};

/// What is needed from a NEXUS agent to make a character.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
#[serde(rename_all = "camelCase", default)]
pub struct AgentSeed {
    pub id: String,
    pub name: String,
    pub role: String,
    pub is_central: bool,
    pub model: Option<String>,
    pub power: Option<String>,
    pub skills_enabled: bool,
    pub connections: Vec<String>,
    pub recent_tasks: Vec<String>,
}

fn slug(s: &str) -> String {
    pcc_core::ids::slugify(s)
}

/// One character per agent, linked to it; workers report to Central.
pub fn from_agents(agents: &[AgentSeed]) -> Vec<Character> {
    let central = agents.iter().find(|a| a.is_central).map(|a| a.name.clone());
    agents
        .iter()
        .enumerate()
        .map(|(i, a)| {
            let mut relationships = Vec::new();
            if a.is_central {
                for w in agents.iter().filter(|w| !w.is_central) {
                    relationships.push(Relationship { with: w.name.clone(), kind: "coordinates".into() });
                }
            } else if let Some(c) = &central {
                relationships.push(Relationship { with: c.clone(), kind: "reports to".into() });
            }
            let mut goals = vec![if a.is_central {
                "Keep the team on track and deliver missions".to_string()
            } else {
                format!("Deliver work as {}", a.role)
            }];
            goals.extend(a.recent_tasks.iter().take(3).cloned());
            Character {
                id: slug(&a.name),
                name: a.name.clone(),
                nexus_agent: Some(a.id.clone()),
                personality: if a.is_central {
                    "the calm orchestrator of the team".into()
                } else {
                    format!("a focused specialist: {}", a.role)
                },
                goals,
                skills: if a.skills_enabled { vec!["Claude Code skills".into()] } else { vec![] },
                tools: vec!["Claude Code".into()],
                mcp: a.connections.clone(),
                model: a.model.clone(),
                autonomy: a.power.clone().unwrap_or_else(|| "custom".into()),
                relationships,
                sprite: format!("f{}", i % 8 + 1),
                x: 38.0,
                y: 19.0,
                ..Default::default()
            }
        })
        .collect()
}

/// Runs a one-shot Claude Code prompt without tools and returns its text.
fn ask_claude(claude: &Path, model: &str, prompt: &str, budget_usd: f64) -> Result<String> {
    let dir = std::env::temp_dir();
    let out = pcc_claude::process::std_command(claude)
        .args([
            "-p",
            "--output-format",
            "json",
            "--model",
            model,
            "--tools",
            "",
            "--strict-mcp-config",
            "--disable-slash-commands",
            "--no-session-persistence",
            "--max-budget-usd",
            &format!("{budget_usd:.2}"),
            prompt,
        ])
        .current_dir(dir)
        .output()
        .map_err(|e| Error::Process(format!("cannot run Claude Code: {e}")))?;
    let v: Value = serde_json::from_slice(&out.stdout).map_err(|_| {
        Error::Process(format!("unexpected Claude Code output: {}", String::from_utf8_lossy(&out.stderr).trim()))
    })?;
    if v.get("is_error").and_then(Value::as_bool).unwrap_or(false) {
        return Err(Error::Process(v.get("result").and_then(Value::as_str).unwrap_or("Claude Code error").into()));
    }
    Ok(v.get("result").and_then(Value::as_str).unwrap_or("").to_string())
}

/// Extracts the first JSON array from a model answer (tolerates code fences).
pub fn json_array(text: &str) -> Result<Vec<Value>> {
    let start = text.find('[').ok_or_else(|| Error::invalid("no JSON array in the answer"))?;
    let end = text.rfind(']').ok_or_else(|| Error::invalid("no JSON array in the answer"))?;
    serde_json::from_str(&text[start..=end]).map_err(|e| Error::invalid(format!("invalid JSON from Claude: {e}")))
}

/// Asks Claude for `count` characters fitting the description. Blocking; costs tokens.
pub fn generate(claude: &Path, model: &str, description: &str, count: usize) -> Result<Vec<Character>> {
    let prompt = format!(
        "Create {count} distinct characters for a small simulated world described as: {description}\n\
         Answer ONLY with a JSON array of objects with keys: name (string), personality (one sentence), \
         goals (array of 1-3 short strings), skills (array of strings)."
    );
    let raw = ask_claude(claude, model, &prompt, 0.25)?;
    let items = json_array(&raw)?;
    Ok(items
        .into_iter()
        .take(count)
        .enumerate()
        .filter_map(|(i, v)| {
            let name = v.get("name")?.as_str()?.to_string();
            let list = |k: &str| {
                v.get(k)
                    .and_then(Value::as_array)
                    .map(|a| a.iter().filter_map(|x| x.as_str().map(str::to_string)).collect())
                    .unwrap_or_default()
            };
            Some(Character {
                id: slug(&name),
                personality: v.get("personality").and_then(Value::as_str).unwrap_or("").to_string(),
                goals: list("goals"),
                skills: list("skills"),
                sprite: format!("f{}", i % 8 + 1),
                autonomy: "normal".into(),
                x: 10.0,
                y: 16.0,
                name,
                ..Default::default()
            })
        })
        .collect())
}

/// Generates a short simulated conversation between two characters. Blocking; costs tokens.
pub fn converse(
    claude: &Path,
    model: &str,
    world: &str,
    a: &Character,
    b: &Character,
    room: &str,
) -> Result<Vec<ConversationLine>> {
    let prompt = format!(
        "Simulated world: {world}. In the {room}, {} ({}; goals: {}) meets {} ({}; goals: {}).\n\
         Write their short conversation: 4 to 6 lines. Answer ONLY with a JSON array of {{\"speaker\": name, \"text\": line}}.",
        a.name, a.personality, a.goals.join("; "), b.name, b.personality, b.goals.join("; ")
    );
    let raw = ask_claude(claude, model, &prompt, 0.10)?;
    Ok(json_array(&raw)?
        .into_iter()
        .filter_map(|v| {
            Some(ConversationLine {
                speaker: v.get("speaker")?.as_str()?.to_string(),
                text: v.get("text")?.as_str()?.to_string(),
                ts: pcc_core::now(),
            })
        })
        .collect())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn agents_become_linked_characters() {
        let seeds = vec![
            AgentSeed {
                id: "central".into(),
                name: "Central".into(),
                role: "Orchestrator".into(),
                is_central: true,
                ..Default::default()
            },
            AgentSeed {
                id: "roblox".into(),
                name: "Roblox Agent".into(),
                role: "Roblox systems".into(),
                skills_enabled: true,
                connections: vec!["roblox-studio".into()],
                recent_tasks: vec!["Implement drone formation".into()],
                ..Default::default()
            },
        ];
        let c = from_agents(&seeds);
        assert_eq!(c[0].nexus_agent.as_deref(), Some("central"));
        assert_eq!(c[0].relationships[0].with, "Roblox Agent");
        assert_eq!(c[1].relationships[0].kind, "reports to");
        assert_eq!(c[1].mcp, vec!["roblox-studio"]);
        assert!(c[1].goals.contains(&"Implement drone formation".to_string()));
        assert_ne!(c[0].sprite, c[1].sprite);
    }

    #[test]
    fn extracts_json_arrays_from_answers() {
        assert_eq!(json_array("Here:\n```json\n[{\"a\":1}]\n```").unwrap().len(), 1);
        assert!(json_array("no json").is_err());
    }
}
