//! AI World: a 2D world representing the agent team.
//!
//! * `model`      – world state (rooms, characters, conversations, events).
//! * `engine`     – tick-based movement; hybrid characters mirror real agents.
//! * `characters` – characters from NEXUS agents, custom or generated by Claude.
//! * `providers`  – `AIWorldProvider`: native, AI Town compatible, AI Town fork, custom.
//!
//! Inspired by the architecture of a16z-infra/ai-town (MIT): world state,
//! simulation engine stepping by ticks, agents with memory/goals, client.

pub mod characters;
pub mod engine;
pub mod model;
pub mod providers;

use std::path::{Path, PathBuf};

use pcc_core::{Error, Result};

pub use model::{Character, World, WorldMode};

/// `.agent-project/ai-world/world.json`
pub fn world_file(project_root: &Path) -> PathBuf {
    project_root.join(".agent-project").join("ai-world").join("world.json")
}

pub fn load(project_root: &Path) -> Result<Option<World>> {
    match std::fs::read_to_string(world_file(project_root)) {
        Ok(s) => Ok(Some(serde_json::from_str(&s).map_err(|e| Error::Storage(format!("world.json: {e}")))?)),
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(None),
        Err(e) => Err(e.into()),
    }
}

pub fn save(project_root: &Path, world: &World) -> Result<()> {
    let path = world_file(project_root);
    if let Some(dir) = path.parent() {
        std::fs::create_dir_all(dir)?;
    }
    let tmp = path.with_extension("tmp~");
    std::fs::write(&tmp, serde_json::to_vec_pretty(world)?)?;
    std::fs::rename(tmp, path)?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn save_and_load() {
        let tmp = tempfile::tempdir().unwrap();
        assert!(load(tmp.path()).unwrap().is_none());
        let w = World::new("Town", "d", "nexus_native", WorldMode::Hybrid);
        save(tmp.path(), &w).unwrap();
        assert_eq!(load(tmp.path()).unwrap().unwrap().name, "Town");
    }
}
