//! World state: map, characters, conversations. Persisted as
//! `.agent-project/ai-world/world.json`.

use serde::{Deserialize, Serialize};

pub const WORLD_FORMAT: u32 = 1;

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum WorldMode {
    /// Characters live only in the world; nothing touches the real project.
    Simulation,
    /// Characters mirror real NEXUS agents (positions follow their real state).
    Hybrid,
    /// Hybrid, and characters' actions may be turned into real missions.
    RealExecution,
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum RoomKind {
    /// Agents running a turn (coding, editing, testing).
    Workshop,
    /// Tasks in review.
    Review,
    /// Agents exchanging messages.
    Meeting,
    /// Idle / waiting agents.
    Lounge,
    /// Agents using SSH, MCP or other connections.
    ServerRoom,
    /// Agents blocked on a permission or user request.
    Security,
    /// Offline / stopped agents.
    Gate,
    /// Crashed agents.
    Infirmary,
    /// Memory / documentation work.
    Library,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct Room {
    pub id: String,
    pub name: String,
    pub kind: RoomKind,
    pub x: f32,
    pub y: f32,
    pub w: f32,
    pub h: f32,
}

impl Room {
    pub fn center(&self) -> (f32, f32) {
        (self.x + self.w / 2.0, self.y + self.h / 2.0)
    }
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
#[serde(rename_all = "camelCase", default)]
pub struct Relationship {
    pub with: String,
    pub kind: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
#[serde(rename_all = "camelCase", default)]
pub struct Character {
    pub id: String,
    pub name: String,
    /// Linked NEXUS agent (hybrid / real execution).
    pub nexus_agent: Option<String>,
    pub personality: String,
    pub goals: Vec<String>,
    /// Short long-term memories of the character (simulation).
    pub memory: Vec<String>,
    pub skills: Vec<String>,
    pub tools: Vec<String>,
    pub mcp: Vec<String>,
    pub model: Option<String>,
    /// `low` | `normal` | `high` | `maximum` (descriptive in simulation).
    pub autonomy: String,
    pub relationships: Vec<Relationship>,
    /// Sprite id for renderers (AI Town uses f1..f8).
    pub sprite: String,
    pub x: f32,
    pub y: f32,
    pub room: Option<String>,
    pub target_room: Option<String>,
    /// What the character is doing: the real current action when linked.
    pub activity: Option<String>,
    /// Simulated mood (simulation mode only; `None` for linked characters).
    pub mood: Option<String>,
    pub last_action: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
#[serde(rename_all = "camelCase", default)]
pub struct ConversationLine {
    pub speaker: String,
    pub text: String,
    pub ts: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
#[serde(rename_all = "camelCase", default)]
pub struct Conversation {
    pub id: String,
    pub participants: Vec<String>,
    pub room: Option<String>,
    pub lines: Vec<ConversationLine>,
    /// `simulated` (generated by Claude in simulation) or `real` (NEXUS messages).
    pub origin: String,
    pub started_at: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
#[serde(rename_all = "camelCase", default)]
pub struct WorldEvent {
    pub ts: String,
    pub character: Option<String>,
    pub text: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase", default)]
pub struct WorldSettings {
    /// Ticks per second while running.
    pub speed: f32,
    /// Generate simulated conversations with Claude (costs tokens).
    pub llm_conversations: bool,
    pub conversation_model: String,
    pub max_conversations_per_hour: u32,
    pub rules: Vec<String>,
    pub environment: String,
}

impl Default for WorldSettings {
    fn default() -> Self {
        Self {
            speed: 2.0,
            llm_conversations: false,
            conversation_model: "haiku".into(),
            max_conversations_per_hour: 6,
            rules: vec![],
            environment: "Agent campus".into(),
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct World {
    pub format: u32,
    pub name: String,
    pub description: String,
    /// `nexus_native`, `ai_town` or `custom`.
    pub provider: String,
    pub mode: WorldMode,
    pub running: bool,
    pub tick: u64,
    pub width: f32,
    pub height: f32,
    pub rooms: Vec<Room>,
    pub characters: Vec<Character>,
    pub conversations: Vec<Conversation>,
    pub events: Vec<WorldEvent>,
    pub settings: WorldSettings,
    /// Provider data (e.g. AI Town folder and setup state).
    #[serde(default)]
    pub provider_state: serde_json::Value,
    pub created_at: String,
}

/// Campus map: one room per kind of real activity.
pub fn default_rooms() -> Vec<Room> {
    let r = |id: &str, name: &str, kind, x, y, w, h| Room { id: id.into(), name: name.into(), kind, x, y, w, h };
    vec![
        r("workshop", "Workshop", RoomKind::Workshop, 2.0, 2.0, 16.0, 9.0),
        r("review", "Review Room", RoomKind::Review, 20.0, 2.0, 9.0, 6.0),
        r("meeting", "Meeting Room", RoomKind::Meeting, 31.0, 2.0, 9.0, 6.0),
        r("library", "Library", RoomKind::Library, 20.0, 10.0, 9.0, 5.0),
        r("server-room", "Server Room", RoomKind::ServerRoom, 31.0, 10.0, 9.0, 5.0),
        r("lounge", "Lounge", RoomKind::Lounge, 2.0, 13.0, 16.0, 8.0),
        r("security", "Security Desk", RoomKind::Security, 20.0, 17.0, 6.0, 4.0),
        r("infirmary", "Infirmary", RoomKind::Infirmary, 28.0, 17.0, 6.0, 4.0),
        r("gate", "Gate", RoomKind::Gate, 36.0, 17.0, 4.0, 4.0),
    ]
}

impl World {
    pub fn new(name: &str, description: &str, provider: &str, mode: WorldMode) -> World {
        World {
            format: WORLD_FORMAT,
            name: name.into(),
            description: description.into(),
            provider: provider.into(),
            mode,
            running: false,
            tick: 0,
            width: 42.0,
            height: 23.0,
            rooms: default_rooms(),
            characters: vec![],
            conversations: vec![],
            events: vec![],
            settings: WorldSettings::default(),
            provider_state: serde_json::Value::Null,
            created_at: pcc_core::now(),
        }
    }

    pub fn room(&self, id: &str) -> Option<&Room> {
        self.rooms.iter().find(|r| r.id == id)
    }

    pub fn room_of_kind(&self, kind: RoomKind) -> Option<&Room> {
        self.rooms.iter().find(|r| r.kind == kind)
    }

    pub fn push_event(&mut self, character: Option<&str>, text: impl Into<String>) {
        self.events.push(WorldEvent {
            ts: pcc_core::now(),
            character: character.map(str::to_string),
            text: text.into(),
        });
        let excess = self.events.len().saturating_sub(300);
        self.events.drain(..excess);
    }
}
