//! The `.agent-project` directory: the persistent brain of a project.

use std::fs;
use std::path::{Path, PathBuf};

use pcc_core::{ProjectInfo, ProjectSettings, Result};

pub const AGENT_DIR: &str = ".agent-project";
pub const FORMAT_VERSION: u32 = 1;

pub const PROJECT_MEMORY_FILES: &[(&str, &str)] = &[
    ("project", "# Project\n\nWhat this project is, who it is for, and its current goals.\n"),
    ("architecture", "# Architecture\n\nMain components, how they fit together, important paths.\n"),
    ("decisions", "# Decisions\n\nDated log of decisions and their reasons.\n"),
    ("conventions", "# Conventions\n\nCoding style, naming, tooling and workflow rules agents must follow.\n"),
    ("discoveries", "# Discoveries\n\nNon-obvious facts learned while working (gotchas, quirks, findings).\n"),
];

const GITIGNORE: &str = "# Generated by Project Control Center.\n\
# Runtime state stays local; memory, plans and task records can be committed.\n\
state.db\nstate.db-*\nlogs/\nsessions/\nworktrees/\n";

/// Resolved paths inside a project.
#[derive(Debug, Clone)]
pub struct Layout {
    pub root: PathBuf,
    pub dir: PathBuf,
}

impl Layout {
    pub fn new(root: impl Into<PathBuf>) -> Self {
        let root = root.into();
        let dir = root.join(AGENT_DIR);
        Layout { root, dir }
    }

    pub fn exists(root: &Path) -> bool {
        root.join(AGENT_DIR).join("project.json").is_file()
    }

    pub fn db_path(&self) -> PathBuf {
        self.dir.join("state.db")
    }
    pub fn project_json(&self) -> PathBuf {
        self.dir.join("project.json")
    }
    pub fn settings_json(&self) -> PathBuf {
        self.dir.join("settings.json")
    }
    pub fn memory_dir(&self) -> PathBuf {
        self.dir.join("memory")
    }
    pub fn agent_dir(&self, agent: &str) -> PathBuf {
        self.dir.join("agents").join(agent)
    }
    pub fn tasks_dir(&self, bucket: &str) -> PathBuf {
        self.dir.join("tasks").join(bucket)
    }
    pub fn messages_dir(&self) -> PathBuf {
        self.dir.join("messages")
    }
    pub fn sessions_dir(&self) -> PathBuf {
        self.dir.join("sessions")
    }
    pub fn logs_dir(&self) -> PathBuf {
        self.dir.join("logs")
    }
    pub fn plans_dir(&self) -> PathBuf {
        self.dir.join("plans")
    }
    pub fn snapshots_dir(&self) -> PathBuf {
        self.dir.join("snapshots")
    }
    /// UI workspace layout (tabs and panel tree), owned by the UI.
    pub fn workspace_json(&self) -> PathBuf {
        self.dir.join("settings").join("workspace.json")
    }
    pub fn worktrees_dir(&self) -> PathBuf {
        self.dir.join("worktrees")
    }

    /// Creates every directory and default file that is missing. Idempotent.
    pub fn ensure(&self) -> Result<()> {
        for d in [
            self.dir.clone(),
            self.memory_dir(),
            self.dir.join("agents"),
            self.tasks_dir("active"),
            self.tasks_dir("completed"),
            self.tasks_dir("failed"),
            self.messages_dir(),
            self.sessions_dir(),
            self.logs_dir(),
            self.plans_dir(),
            self.snapshots_dir(),
        ] {
            fs::create_dir_all(&d)?;
        }
        for (name, template) in PROJECT_MEMORY_FILES {
            let p = self.memory_dir().join(format!("{name}.md"));
            if !p.exists() {
                fs::write(p, template)?;
            }
        }
        let gi = self.dir.join(".gitignore");
        if !gi.exists() {
            fs::write(gi, GITIGNORE)?;
        }
        Ok(())
    }

    pub fn ensure_agent_dir(&self, agent: &str, role: &str) -> Result<()> {
        let d = self.agent_dir(agent);
        fs::create_dir_all(&d)?;
        let mem = d.join("memory.md");
        if !mem.exists() {
            fs::write(mem, format!("# {agent} memory\n\nRole: {role}\n\n"))?;
        }
        Ok(())
    }

    pub fn write_project(&self, info: &ProjectInfo) -> Result<()> {
        write_json_atomic(&self.project_json(), info)
    }

    pub fn read_project(&self) -> Result<ProjectInfo> {
        Ok(serde_json::from_str(&fs::read_to_string(self.project_json())?)?)
    }

    pub fn write_settings(&self, s: &ProjectSettings) -> Result<()> {
        write_json_atomic(&self.settings_json(), s)
    }

    /// Missing or partial settings fall back to defaults field by field.
    pub fn read_settings(&self) -> Result<ProjectSettings> {
        match fs::read_to_string(self.settings_json()) {
            Ok(s) => Ok(serde_json::from_str(&s)?),
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(ProjectSettings::default()),
            Err(e) => Err(e.into()),
        }
    }
}

/// Writes JSON through a temp file + rename so a crash never leaves a half-written file.
pub fn write_json_atomic<T: serde::Serialize>(path: &Path, value: &T) -> Result<()> {
    write_atomic(path, serde_json::to_string_pretty(value)?.as_bytes())
}

pub fn write_atomic(path: &Path, bytes: &[u8]) -> Result<()> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    let tmp = path.with_extension("tmp~");
    fs::write(&tmp, bytes)?;
    fs::rename(&tmp, path)?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn ensure_creates_tree_and_is_idempotent() {
        let tmp = tempfile::tempdir().unwrap();
        let l = Layout::new(tmp.path());
        l.ensure().unwrap();
        fs::write(l.memory_dir().join("project.md"), "custom").unwrap();
        l.ensure().unwrap();
        assert_eq!(fs::read_to_string(l.memory_dir().join("project.md")).unwrap(), "custom");
        for d in ["tasks/active", "tasks/completed", "tasks/failed", "messages", "plans", "snapshots"] {
            assert!(l.dir.join(d).is_dir(), "{d}");
        }
        assert!(l.dir.join(".gitignore").is_file());
    }

    #[test]
    fn settings_default_when_missing_or_partial() {
        let tmp = tempfile::tempdir().unwrap();
        let l = Layout::new(tmp.path());
        l.ensure().unwrap();
        assert_eq!(l.read_settings().unwrap(), ProjectSettings::default());
        fs::write(l.settings_json(), r#"{"maxParallelWorkers": 7}"#).unwrap();
        let s = l.read_settings().unwrap();
        assert_eq!(s.max_parallel_workers, 7);
        assert!(s.use_worktrees);
    }
}
