import { useMemo } from "react";
import { Tabs } from "../../components/Tabs";
import { formatClock } from "../../lib/format";
import type { World } from "../../lib/types";
import { newestFirst } from "./frames";

const ORIGIN_LABEL: Record<string, string> = {
  simulated: "simulated (generated by Claude)",
  real: "real NEXUS messages",
};

export type FeedTab = "events" | "conversations";

/** World events (newest first) and conversations with their origin. */
export function WorldFeed({ world, tab, onTab }: { world: World; tab: FeedTab; onTab: (t: FeedTab) => void }) {
  const names = useMemo(() => new Map(world.characters.map((c) => [c.id, c.name])), [world.characters]);
  const events = useMemo(() => newestFirst(world.events, 80), [world.events]);
  const conversations = useMemo(
    () => [...world.conversations].sort((a, b) => b.startedAt.localeCompare(a.startedAt)).slice(0, 30),
    [world.conversations],
  );
  const name = (id: string) => names.get(id) ?? id;

  return (
    <div className="world-feed">
      <Tabs
        tabs={[
          { key: "events", label: `Events (${world.events.length})` },
          { key: "conversations", label: `Conversations (${world.conversations.length})` },
        ]}
        active={tab}
        onChange={onTab}
      />
      <div className="world-feed-body">
        {tab === "events" &&
          (events.length === 0 ? (
            <div className="small muted pad">No events yet. Run the world to see characters move.</div>
          ) : (
            <ul>
              {events.map((e, i) => (
                <li key={`${e.ts}-${i}`} className="world-event">
                  <span className="tiny mono dim">{formatClock(e.ts)}</span> <span>{e.text}</span>
                </li>
              ))}
            </ul>
          ))}
        {tab === "conversations" &&
          (conversations.length === 0 ? (
            <div className="small muted pad">No conversations yet. In Hybrid / Real execution, messages between linked agents appear here; otherwise select a character and use “Talk with…”.</div>
          ) : (
            conversations.map((c) => (
              <div key={c.id} className="world-conv">
                <div className="row tiny">
                  <strong>{c.participants.map(name).join(" & ")}</strong>
                  {c.room && <span className="muted">in {c.room}</span>}
                  <span className={`chip ${c.origin === "real" ? "tone-green" : "tone-grey"}`}>
                    {ORIGIN_LABEL[c.origin] ?? c.origin}
                  </span>
                  <span className="spacer" />
                  <span className="dim mono">{formatClock(c.startedAt)}</span>
                </div>
                {c.lines.map((l, i) => (
                  <div key={i} className="small">
                    <span className="muted">{name(l.speaker)}:</span> {l.text}
                  </div>
                ))}
              </div>
            ))
          ))}
      </div>
    </div>
  );
}
